-- Query to monitor warehouse costs and performance
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('day', START_TIME) AS usage_date,
    SUM(CREDITS_USED) AS total_credits,
    SUM(CREDITS_USED) * 3.00 AS estimated_cost_usd,
    COUNT(*) AS query_count,
    AVG(TOTAL_ELAPSED_TIME) / 1000 AS avg_query_seconds,
    MAX(TOTAL_ELAPSED_TIME) / 1000 AS max_query_seconds,
    AVG(QUEUED_OVERLOAD_TIME) / 1000 AS avg_queue_time,
    SUM(CREDITS_USED_BY_WAREHOUSE) AS warehouse_credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('day', START_TIME)
ORDER BY usage_date DESC, total_credits DESC;

-- Query to monitor warehouse utilization
SELECT 
    W.NAME AS warehouse_name,
    W.WAREHOUSE_SIZE,
    W.STATE AS current_state,
    W.QUEUED_LOAD,
    W.RUNNING,
    W.QUOTA_PERCENTAGE,
    W.AUTO_SUSPEND,
    W.AUTO_RESUME,
    W.RESOURCE_MONITOR_ELAPSED_TIME,
    W.CREATION_TIME,
    W.LAST_RESUMED_TIME,
    W.LAST_SUSPENDED_TIME,
    W.LAST_ALTERED_TIME
FROM SNOWFLAKE.INFORMATION_SCHEMA.WAREHOUSES W
WHERE W.DELETED IS NULL
ORDER BY W.NAME;

-- Query to monitor query performance
SELECT 
    QUERY_ID,
    USER_NAME,
    WAREHOUSE_NAME,
    QUERY_TEXT,
    DATABASE_NAME,
    SCHEMA_NAME,
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME / 1000 AS duration_seconds,
    BYTES_SCANNED / 1024 / 1024 / 1024 AS gb_scanned,
    BYTES_WRITTEN / 1024 / 1024 / 1024 AS gb_written,
    ROWS_PRODUCED,
    COMPILATION_TIME / 1000 AS compilation_seconds,
    EXECUTION_TIME / 1000 AS execution_seconds,
    WAREHOUSE_SIZE,
    WAREHOUSE_TYPE,
    QUERY_TYPE,
    SESSION_ID,
    ERROR_CODE,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME LIKE 'TRAFFIC_%'
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 100;

-- Query to monitor table sizes and storage costs
SELECT 
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT,
    BYTES / 1024 / 1024 / 1024 AS table_size_gb,
    CLUSTERING_KEY,
    CREATED,
    LAST_ALTERED,
    AUTO_CLUSTERING_ON,
    COMMENT
FROM SNOWFLAKE.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('RAW', 'STAGING', 'ANALYTICS', 'ML_OUTPUT')
  AND TABLE_CATALOG = 'TRAFFIC_DB'
ORDER BY BYTES DESC;

-- Query to monitor data transfer costs
SELECT 
    START_TIME,
    END_TIME,
    CLOUD,
    REGION,
    TRANSFER_TYPE,
    BYTES_TRANSFERRED / 1024 / 1024 / 1024 AS gb_transferred,
    STORAGE_LOCATION,
    CREDITS_USED,
    CREDITS_USED * 3.00 AS estimated_cost_usd
FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;

-- Query to monitor warehouse auto-scaling events
SELECT 
    WAREHOUSE_NAME,
    START_TIME,
    END_TIME,
    CREDITS_USED,
    WAREHOUSE_SIZE,
    CLUSTER_NUMBER,
    IS_AUTO_RESUMED,
    IS_AUTO_SUSPENDED,
    IS_SUSPENDED_MANUALLY,
    IS_RESUMED_MANUALLY
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME LIKE 'TRAFFIC_%'
ORDER BY START_TIME DESC;

-- Create cost monitoring view
CREATE OR REPLACE VIEW TRAFFIC_DB.ANALYTICS.WAREHOUSE_COST_MONITORING AS
SELECT 
    WAREHOUSE_NAME,
    DATE_TRUNC('day', START_TIME) AS usage_date,
    SUM(CREDITS_USED) AS total_credits,
    SUM(CREDITS_USED) * 3.00 AS estimated_cost_usd,
    COUNT(*) AS query_count,
    AVG(TOTAL_ELAPSED_TIME) / 1000 AS avg_query_seconds,
    MAX(TOTAL_ELAPSED_TIME) / 1000 AS max_query_seconds,
    AVG(QUEUED_OVERLOAD_TIME) / 1000 AS avg_queue_time
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('day', START_TIME);

-- Create performance monitoring view
CREATE OR REPLACE VIEW TRAFFIC_DB.ANALYTICS.QUERY_PERFORMANCE_MONITORING AS
SELECT 
    QUERY_ID,
    USER_NAME,
    WAREHOUSE_NAME,
    QUERY_TEXT,
    DATABASE_NAME,
    SCHEMA_NAME,
    START_TIME,
    TOTAL_ELAPSED_TIME / 1000 AS duration_seconds,
    BYTES_SCANNED / 1024 / 1024 / 1024 AS gb_scanned,
    BYTES_WRITTEN / 1024 / 1024 / 1024 AS gb_written,
    ROWS_PRODUCED,
    COMPILATION_TIME / 1000 AS compilation_seconds,
    EXECUTION_TIME / 1000 AS execution_seconds,
    WAREHOUSE_SIZE,
    QUERY_TYPE,
    ERROR_CODE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME LIKE 'TRAFFIC_%';

-- Grant access to monitoring views
GRANT SELECT ON VIEW TRAFFIC_DB.ANALYTICS.WAREHOUSE_COST_MONITORING TO ROLE TRAFFIC_ADMIN;
GRANT SELECT ON VIEW TRAFFIC_DB.ANALYTICS.QUERY_PERFORMANCE_MONITORING TO ROLE TRAFFIC_ADMIN;
GRANT SELECT ON VIEW TRAFFIC_DB.ANALYTICS.WAREHOUSE_COST_MONITORING TO ROLE TRAFFIC_TRANSFORMER;
GRANT SELECT ON VIEW TRAFFIC_DB.ANALYTICS.QUERY_PERFORMANCE_MONITORING TO ROLE TRAFFIC_TRANSFORMER;
