-- Create roles for different access levels
CREATE ROLE IF NOT EXISTS TRAFFIC_LOADER;
CREATE ROLE IF NOT EXISTS TRAFFIC_TRANSFORMER;
CREATE ROLE IF NOT EXISTS TRAFFIC_ANALYST;
CREATE ROLE IF NOT EXISTS TRAFFIC_ML_CONSUMER;
CREATE ROLE IF NOT EXISTS TRAFFIC_ADMIN;

-- Grant warehouse usage to roles
-- Loader: can write to RAW schema only
GRANT USAGE ON WAREHOUSE TRAFFIC_LOAD_WH TO ROLE TRAFFIC_LOADER;
GRANT USAGE ON DATABASE TRAFFIC_DB TO ROLE TRAFFIC_LOADER;
GRANT USAGE ON SCHEMA TRAFFIC_DB.RAW TO ROLE TRAFFIC_LOADER;
GRANT ALL ON SCHEMA TRAFFIC_DB.RAW TO ROLE TRAFFIC_LOADER;
GRANT ALL ON ALL TABLES IN SCHEMA TRAFFIC_DB.RAW TO ROLE TRAFFIC_LOADER;
GRANT ALL ON ALL STAGES IN SCHEMA TRAFFIC_DB.RAW TO ROLE TRAFFIC_LOADER;
GRANT ALL ON ALL PIPES IN SCHEMA TRAFFIC_DB.RAW TO ROLE TRAFFIC_LOADER;

-- Transformer (DBT): can read RAW, write STAGING + ANALYTICS
GRANT USAGE ON WAREHOUSE TRAFFIC_TRANSFORM_WH TO ROLE TRAFFIC_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRAFFIC_DB TO ROLE TRAFFIC_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA TRAFFIC_DB.RAW TO ROLE TRAFFIC_TRANSFORMER;
GRANT ALL ON SCHEMA TRAFFIC_DB.STAGING TO ROLE TRAFFIC_TRANSFORMER;
GRANT ALL ON SCHEMA TRAFFIC_DB.ANALYTICS TO ROLE TRAFFIC_TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA TRAFFIC_DB.STAGING TO ROLE TRAFFIC_TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA TRAFFIC_DB.ANALYTICS TO ROLE TRAFFIC_TRANSFORMER;

-- Analyst (Tableau): read-only on ANALYTICS
GRANT USAGE ON WAREHOUSE TRAFFIC_ANALYTICS_WH TO ROLE TRAFFIC_ANALYST;
GRANT USAGE ON SCHEMA TRAFFIC_DB.ANALYTICS TO ROLE TRAFFIC_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TRAFFIC_DB.ANALYTICS TO ROLE TRAFFIC_ANALYST;

-- ML Consumer: can read ANALYTICS, write ML_OUTPUT
GRANT USAGE ON WAREHOUSE TRAFFIC_ML_WH TO ROLE TRAFFIC_ML_CONSUMER;
GRANT USAGE ON SCHEMA TRAFFIC_DB.ANALYTICS TO ROLE TRAFFIC_ML_CONSUMER;
GRANT USAGE ON SCHEMA TRAFFIC_DB.ML_OUTPUT TO ROLE TRAFFIC_ML_CONSUMER;
GRANT SELECT ON ALL TABLES IN SCHEMA TRAFFIC_DB.ANALYTICS TO ROLE TRAFFIC_ML_CONSUMER;
GRANT ALL ON SCHEMA TRAFFIC_DB.ML_OUTPUT TO ROLE TRAFFIC_ML_CONSUMER;
GRANT ALL ON ALL TABLES IN SCHEMA TRAFFIC_DB.ML_OUTPUT TO ROLE TRAFFIC_ML_CONSUMER;

-- Admin: full access
GRANT USAGE ON ALL WAREHOUSES TO ROLE TRAFFIC_ADMIN;
GRANT USAGE ON DATABASE TRAFFIC_DB TO ROLE TRAFFIC_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRAFFIC_DB TO ROLE TRAFFIC_ADMIN;
GRANT ALL ON ALL TABLES IN DATABASE TRAFFIC_DB TO ROLE TRAFFIC_ADMIN;

-- Column-level security: mask lat/lon for analyst role
CREATE OR REPLACE MASKING POLICY lat_lon_mask AS (val FLOAT) RETURNS FLOAT ->
  CASE 
    WHEN CURRENT_ROLE() IN ('TRAFFIC_ANALYST') THEN ROUND(val, 1) 
    ELSE val 
  END;

CREATE OR REPLACE MASKING POLICY sensor_id_mask AS (val VARCHAR) RETURNS VARCHAR ->
  CASE 
    WHEN CURRENT_ROLE() IN ('TRAFFIC_ANALYST') THEN CONCAT(LEFT(val, 3), '***') 
    ELSE val 
  END;

-- Apply masking policies
ALTER TABLE TRAFFIC_DB.RAW.TRAFFIC_EVENTS MODIFY COLUMN latitude SET MASKING POLICY lat_lon_mask;
ALTER TABLE TRAFFIC_DB.RAW.TRAFFIC_EVENTS MODIFY COLUMN longitude SET MASKING POLICY lat_lon_mask;
ALTER TABLE TRAFFIC_DB.RAW.TRAFFIC_EVENTS MODIFY COLUMN sensor_id SET MASKING POLICY sensor_id_mask;

ALTER TABLE TRAFFIC_DB.ANALYTICS.MART_HOURLY_TRAFFIC MODIFY COLUMN latitude SET MASKING POLICY lat_lon_mask;
ALTER TABLE TRAFFIC_DB.ANALYTICS.MART_HOURLY_TRAFFIC MODIFY COLUMN longitude SET MASKING POLICY lat_lon_mask;

-- Row access policies for data governance
CREATE OR REPLACE ROW ACCESS POLICY traffic_data_filter AS (region VARCHAR) RETURNS BOOLEAN ->
  CASE 
    WHEN CURRENT_ROLE() IN ('TRAFFIC_ADMIN') THEN TRUE
    WHEN CURRENT_ROLE() IN ('TRAFFIC_LOADER') THEN TRUE
    WHEN CURRENT_ROLE() IN ('TRAFFIC_TRANSFORMER') THEN TRUE
    WHEN CURRENT_ROLE() IN ('TRAFFIC_ML_CONSUMER') THEN TRUE
    WHEN CURRENT_ROLE() IN ('TRAFFIC_ANALYST') AND region = 'US' THEN TRUE
    ELSE FALSE
  END;

-- Apply row access policies (if region column exists)
-- ALTER TABLE TRAFFIC_DB.ANALYTICS.MART_HOURLY_TRAFFIC ADD ROW ACCESS POLICY traffic_data_filter ON (region);

-- Grant roles to users (example users)
-- In production, these would be actual user accounts
GRANT ROLE TRAFFIC_LOADER TO USER traffic_loader_user;
GRANT ROLE TRAFFIC_TRANSFORMER TO USER dbt_user;
GRANT ROLE TRAFFIC_ANALYST TO USER tableau_user;
GRANT ROLE TRAFFIC_ML_CONSUMER TO USER ml_user;
GRANT ROLE TRAFFIC_ADMIN TO USER admin_user;

-- Set default roles
ALTER USER traffic_loader_user SET DEFAULT_ROLE = TRAFFIC_LOADER;
ALTER USER dbt_user SET DEFAULT_ROLE = TRAFFIC_TRANSFORMER;
ALTER USER tableau_user SET DEFAULT_ROLE = TRAFFIC_ANALYST;
ALTER USER ml_user SET DEFAULT_ROLE = TRAFFIC_ML_CONSUMER;
ALTER USER admin_user SET DEFAULT_ROLE = TRAFFIC_ADMIN;

-- Create network policies for security
CREATE OR REPLACE NETWORK POLICY TRAFFIC_ALLOWED_IPS AS (src_ip VARCHAR) RETURNS BOOLEAN ->
  CASE 
    WHEN CURRENT_ROLE() IN ('TRAFFIC_ADMIN') THEN TRUE
    WHEN src_ip LIKE '192.168.%' THEN TRUE  -- Internal network
    WHEN src_ip LIKE '10.%' THEN TRUE        -- AWS internal
    ELSE FALSE
  END;

-- Apply network policies to warehouses
ALTER WAREHOUSE TRAFFIC_LOAD_WH SET NETWORK_POLICY = TRAFFIC_ALLOWED_IPS;
ALTER WAREHOUSE TRAFFIC_TRANSFORM_WH SET NETWORK_POLICY = TRAFFIC_ALLOWED_IPS;
ALTER WAREHOUSE TRAFFIC_ANALYTICS_WH SET NETWORK_POLICY = TRAFFIC_ALLOWED_IPS;
ALTER WAREHOUSE TRAFFIC_ML_WH SET NETWORK_POLICY = TRAFFIC_ALLOWED_IPS;

-- Log RBAC setup
SELECT 'RBAC and security policies setup completed' AS status;
