-- Snowpipe for auto-ingestion when new files land in S3
CREATE OR REPLACE PIPE TRAFFIC_DB.RAW.TRAFFIC_PIPE
  AUTO_INGEST = TRUE
  AS
  COPY INTO TRAFFIC_DB.RAW.TRAFFIC_EVENTS
  FROM @TRAFFIC_DB.RAW.S3_TRAFFIC_STAGE
  FILE_FORMAT = (TYPE = 'PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE'
  PURGE = TRUE
  COMMENT = 'Auto-ingest traffic events from Delta Lake';

CREATE OR REPLACE PIPE TRAFFIC_DB.RAW.WEATHER_PIPE
  AUTO_INGEST = TRUE
  AS
  COPY INTO TRAFFIC_DB.RAW.WEATHER_UPDATES
  FROM @TRAFFIC_DB.RAW.S3_WEATHER_STAGE
  FILE_FORMAT = (TYPE = 'JSON')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE'
  PURGE = TRUE
  COMMENT = 'Auto-ingest weather updates from S3';

CREATE OR REPLACE PIPE TRAFFIC_DB.RAW.HOLIDAYS_PIPE
  AUTO_INGEST = TRUE
  AS
  COPY INTO TRAFFIC_DB.RAW.HOLIDAYS
  FROM @TRAFFIC_DB.RAW.S3_HOLIDAYS_STAGE
  FILE_FORMAT = (TYPE = 'JSON')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE'
  PURGE = TRUE
  COMMENT = 'Auto-ingest holidays from S3';

CREATE OR REPLACE PIPE TRAFFIC_DB.RAW.SENSORS_PIPE
  AUTO_INGEST = TRUE
  AS
  COPY INTO TRAFFIC_DB.RAW.SENSOR_METADATA
  FROM @TRAFFIC_DB.RAW.S3_SENSORS_STAGE
  FILE_FORMAT = (TYPE = 'JSON')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE'
  PURGE = TRUE
  COMMENT = 'Auto-ingest sensor metadata from S3';

-- Create notification integrations for pipe monitoring
CREATE OR REPLACE NOTIFICATION INTEGRATION TRAFFIC_PIPE_NOTIFICATION
  TYPE = QUEUE
  ENABLED = TRUE
  NOTIFICATION_PROVIDER = AWS_SNS
  AWS_SNS_TOPIC_ARN = 'arn:aws:sns:us-east-1:123456789012:traffic-pipe-notifications'
  COMMENT = 'Notifications for Snowpipe activity';

-- Grant pipe monitoring
GRANT MONITOR ON PIPE TRAFFIC_DB.RAW.TRAFFIC_PIPE TO ROLE SYSADMIN;
GRANT MONITOR ON PIPE TRAFFIC_DB.RAW.WEATHER_PIPE TO ROLE SYSADMIN;
GRANT MONITOR ON PIPE TRAFFIC_DB.RAW.HOLIDAYS_PIPE TO ROLE SYSADMIN;
GRANT MONITOR ON PIPE TRAFFIC_DB.RAW.SENSORS_PIPE TO ROLE SYSADMIN;

-- Check pipe status
SELECT 
    'TRAFFIC_EVENTS' AS pipe_name,
    SYSTEM$PIPE_STATUS('TRAFFIC_DB.RAW.TRAFFIC_PIPE') AS status
UNION ALL
SELECT 
    'WEATHER_UPDATES' AS pipe_name,
    SYSTEM$PIPE_STATUS('TRAFFIC_DB.RAW.WEATHER_PIPE') AS status
UNION ALL
SELECT 
    'HOLIDAYS' AS pipe_name,
    SYSTEM$PIPE_STATUS('TRAFFIC_DB.RAW.HOLIDAYS_PIPE') AS status
UNION ALL
SELECT 
    'SENSORS' AS pipe_name,
    SYSTEM$PIPE_STATUS('TRAFFIC_DB.RAW.SENSORS_PIPE') AS status;
